---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: pl-cloud
namespace: plc
replicas:
- name: api-server
  count: 1
- name: auth-server
  count: 1
- name: profile-server
  count: 1
- name: cloud-proxy
  count: 1
- name: project-manager-server
  count: 1
- name: vzmgr-server
  count: 1
- name: scriptmgr-server
  count: 1
resources:
- ../base
- ../base/ory_auth
- ../overlays/exposed_services_ilb
patchesStrategicMerge:
- artifact_tracker_versions.yaml
- domain_config.yaml
- proxy_envoy.yaml
images:
- name: gcr.io/pixie-oss/pixie-prod/cloud/api_server_image
  newName: songyc31/api_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/artifact_tracker_server_image
  newName: songyc31/artifact_tracker_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/auth_server_image
  newName: songyc31/auth_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/config_manager_server_image
  newName: songyc31/config_manager_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/proxy_server_image
  newName: songyc31/proxy_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/dnsmgr_server_image
  newName: songyc31/dnsmgr_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/indexer_server_image
  newName: songyc31/indexer_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/metrics_server_image
  newName: songyc31/metrics_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/profile_server_image
  newName: songyc31/profile_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/project_manager_server_image
  newName: songyc31/project_manager_server_image
  newTag: latest
- name: songyc31/scriptmgr_server_image
  newName: songyc31/scriptmgr_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/vzconn_server_image
  newName: songyc31/vzconn_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/vzmgr_server_image
  newName: songyc31/vzmgr_server_image
  newTag: latest
- name: gcr.io/pixie-oss/pixie-prod/cloud/job/create_admin_job_image
  newName: songyc31/create_admin_job_image
  newTag: latest
