---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmgr-server
  labels:
    db: pgsql
spec:
  selector:
    matchLabels:
      name: dnsmgr-server
  template:
    metadata:
      labels:
        name: dnsmgr-server
    spec:
      containers:
      - name: dnsmgr-server
        image: songyc31/dnsmgr_server_image
        ports:
        - containerPort: 51900
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 51900
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 51900
        envFrom:
        - configMapRef:
            name: pl-db-config
        - configMapRef:
            name: pl-tls-config
        - configMapRef:
            name: pl-dns-config
        - configMapRef:
            name: pl-domain-config
        env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: cloud-auth-secrets
              key: jwt-signing-key
        - name: PL_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: PL_POSTGRES_USERNAME
        - name: PL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: PL_POSTGRES_PASSWORD
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: cloud-dns-secrets
          mountPath: /secrets/clouddns
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs
      - name: cloud-dns-secrets
        secret:
          secretName: cloud-dns-secrets
          optional: true
